### ISSUE TITLE
Deformation Simulation Input Format

### ISSUE THREAD

**Issue by AhmedAyman1** [zixinyang9109/LiverMatch#2]
Hello,

The V2S-net pipeline takes .stl files as input. However, the 3D-IRCADb-01 dataset is in .vtk format. What have you used to make the conversion? or am I missing something? :)

Thanks

**Comment by zixinyang9109** [comment]
Hello, I used the VTK python library to do this format transformation. Other libraries like meshio and pyvista can do this too.

**Comment by zixinyang9109** [comment]
For using VTK: 

mesh_file = ""
reader = vtkSTLReader()
reader.SetFileName(mesh_file)
reader.Update()
mesh = reader.GetOutput()
mesh = unstructuredGridToPolyData(mesh)
surface = extractSurface(mesh)

# write ply
plyWriter = vtkPLYWriter()
plyWriter.SetFileTypeToASCII()
plyWriter.SetColorModeToOff()
plyWriter.SetInputData(surface)
out_file = mesh_file.replace("vtk", "ply")
plyWriter.SetFileName(out_file)
plyWriter.Write()

**Comment by jfjjdsjdj** [comment]
> Hello
> 
> Yes, I'm trying to reproduce the results and then test my data. It's a pleasure that I can share with you what I understand so far. I think we should use V2S-NET on the dataset to apply the morph. I've downloaded the 3D-IRCADb-01 dataset and only extracted the liver grid file in the .vtk. I excluded data numbers 11, 18, 19, and 20 from the dataset, as described in the paper. Right now, I'm trying to deform the mesh using VS2-NET. If you already have a .vtk grid, V2S-NET should be able to skip unnecessary steps for .stl files, and that's our case. It only requires you to place the .vtk file in the directory where V2S-NET usually stores the files from the previous steps. Alternatively, you can modify the generate.py script to match your directory. I haven't done it myself, but hopefully everything will be fine.

Hi, have you successfully deformed the data? Have you encountered any problems with the installation of the mathutils library, and I was wondering if you had any luck reproducing V2S-Net?

**Comment by jfjjdsjdj** [comment]
> Hello
> 
> Yes, I'm trying to reproduce the results and then test my data. It's a pleasure that I can share with you what I understand so far. I think we should use V2S-NET on the dataset to apply the morph. I've downloaded the 3D-IRCADb-01 dataset and only extracted the liver grid file in the .vtk. I excluded data numbers 11, 18, 19, and 20 from the dataset, as described in the paper. Right now, I'm trying to deform the mesh using VS2-NET. If you already have a .vtk grid, V2S-NET should be able to skip unnecessary steps for .stl files, and that's our case. It only requires you to place the .vtk file in the directory where V2S-NET usually stores the files from the previous steps. Alternatively, you can modify the generate.py script to match your directory. I haven't done it myself, but hopefully everything will be fine.

Hi, have you generated your own deformation data, when I run the generated data it fails, I'd like to ask if it's something to do with libraries such as mathutils vs. bpy, and I'd like to ask you how you handle adding blender as a python extension to the conda environment?

**Comment by AhmedAyman1** [comment]
Hello,

That was a long time ago. But I remember struggling a little bit to make everything right. Here are some of the relavent packages I used to get the results with versions.

gmsh                      4.11.1                   
hdf5                      1.10.6               
matplotlib                3.0.3                    
numpy                     1.18.5                   
pcl                       0.0.0.post1              
python                    3.5.6                
python-dateutil           2.8.2                   
pyyaml                    5.3.1                    
tk                        8.6.12               
vtk                       8.1.2                    
zlib                      1.2.13             

As for bpy, I installed it using snap. But I don't know which version because I have already removed it. 

Best of luck!

**Comment by jfjjdsjdj** [comment]
> Hello,
> 
> That was a long time ago. But I remember struggling a little bit to make everything right. Here are some of the relavent packages I used to get the results with versions.
> 
> gmsh 4.11.1 hdf5 1.10.6 matplotlib 3.0.3 numpy 1.18.5 pcl 0.0.0.post1 python 3.5.6 python-dateutil 2.8.2 pyyaml 5.3.1 tk 8.6.12 vtk 8.1.2 zlib 1.2.13
> 
> I installed bpy using snap version 2.79b.
> 
> Best of luck!

Thank you very much for your help and reply. I installed the binary versions of blender and gmsh, and created the virtual environment under conda, but I still can't show the import of bpy, mathutils, bmesh and other libraries in the IDE, how do you deal with it? I can't seem to find similar tutorials and documentation online, are these libraries downloaded separately, but there are many errors when I install with pip.

**Comment by AhmedAyman1** [comment]
The package versions I have sent you should work. So I advise you to
install the same versions exactly normally using pip and start with python.

**Comment by jfjjdsjdj** [comment]
> The package versions I have sent you should work. So I advise you to install the same versions exactly normally using pip and start with python.

Thank you very much for your help, I have solved the above confusion, it was my problem, I should have gone through the code first instead of obsessing about configuring the environment.
