### ISSUE TITLE
How do you handle the point cloud input？

### ISSUE THREAD

**Issue by jfjjdsjdj** [zixinyang9109/LiverMatch#5]
I downsampled to 1024 points and then input to Kpconv, but it seems to cause sparse points on the surface, which affects the alignment results, may I ask how do you do this, is it a direct input of the full number of points, but this seems to cause the number of clipped points to be inconsistent with the source points.

**Comment by zixinyang9109** [comment]
The original dataset has been downsampled to a reasonable amount of points(see the voxel sizes in the official dataset). So I did not do other processing and the max number of points was set to a high value. Also, the network is small that can handle large numbers of points.

I strongly discouraged to downsample point clouds to a fixed number for the correspondence task. I recommend to do voxelization.

Also, please pay attention to the initial vox size of KPconv.

**Comment by zixinyang9109** [comment]
Augmented R, t sometimes are not optimal due to deformation.

**Comment by jfjjdsjdj** [comment]
Thank you very much，I will try it again.

**Comment by zixinyang9109** [comment]
You are welcome. From my humble opinion, you may try with rigid point clouds. The searching will work well on the rigid points.

**Comment by jfjjdsjdj** [comment]
Oh, this is really a very good suggestion! Is it true that the indexes of the source and target point clouds before and after the deformation are still one-to-one, so that I can confirm the correspondence between tgt and src point clouds by searching for the correspondence between tgt_full and tgt point clouds.

**Comment by zixinyang9109** [comment]
Yes. The deformation field is one-to-one.

**Comment by jfjjdsjdj** [comment]
Thank you very much,  I learn a lot every time

**Comment by zixinyang9109** [comment]
You are very welcome. Please let me know if I can help.
