### ISSUE TITLE
 Learning based method + RANSAC & Rigid ICP 

### ISSUE THREAD

**Issue by YueDai0514** [zixinyang9109/LiverMatch#7]
Hi, I would like to know if the integrated RANSAC-ICP referred to in Livermatch means by rigid initialization and then iterated using the ICP algorithm .

**Comment by YueDai0514** [comment]
I used your method to get around 7000 data for training, and although our RE is slightly higher when compared to Livermatch, we still can't exceed the results in the paper, and I'm wondering if it's a problem that I'm not using ICP, or if it's just the FPFH method that utilizes the ICP algorithm. The amount of data is also another possible factor.

**Comment by YueDai0514** [comment]
Thank you very much for your help! But in the evaluation code
This default setting in the code doesn't seem to mention ICP, I'll try again to integrate other non-rigid methods.

**Comment by zixinyang9109** [comment]
> I used your method to get around 7000 data for training, and although our RE is slightly higher when compared to Livermatch, we still can't exceed the results in the paper, and I'm wondering if it's a problem that I'm not using ICP, or if it's just the FPFH method that utilizes the ICP algorithm. The amount of data is also another possible factor.

> I used your method to get around 7000 data for training, and although our RE is slightly higher when compared to Livermatch, we still can't exceed the results in the paper, and I'm wondering if it's a problem that I'm not using ICP, or if it's just the FPFH method that utilizes the ICP algorithm. The amount of data is also another possible factor.

There are just too many factors, the setting of correspondence_based ICP, the size of data size, the quality of the dataset, how is the dataset processed, the settings of hyper parameters, how the noise is generated. Thus, a good benchmark is really needed. We have been working on that for over one year...Hopefully, hopefully, crying, it can be finished this year.

You can just use SVD on correspondences to get rid of the settings of the open3d one.

**Comment by zixinyang9109** [comment]
> Thank you very much for your help! But in the evaluation code
> 
> This default setting in the code doesn't seem to mention ICP, I'll try again to integrate other non-rigid methods.

The default is here: 

   result_ransac = o3d.pipelines.registration.registration_ransac_based_on_correspondence(
        source=src_pcd_o3d, target=tgt_pcd_o3d, corres=corrs_o3d,
        max_correspondence_distance=distance_threshold,
        estimation_method=o3d.pipelines.registration.TransformationEstimationPointToPoint(False),
        ransac_n=ransac_n
        # criteria=o3d.pipelines.registration.RANSACConvergenceCriteria(50000, 1000)
    )  # criteria=o3d.pi

**Comment by YueDai0514** [comment]
Thank you for your suggestions, I will try again. Livermatch is a great piece of work, my mentor and I have been studying your work in related fields and we are very inspired by your work. Best wishes for your follow-up work.

**Comment by zixinyang9109** [comment]
> Thank you very much for your help! But in the evaluation code
> 
> This default setting in the code doesn't seem to mention ICP, I'll try again to integrate other non-rigid methods.

I am sorry to make you confuse.
We are also working on the non-rigid methods. We find that, if the initial rigid position is good, the non rigid methods work well, especially FEM-based methods. We have not tried to incorporate the correspondence as regularization to non-rigid methods yet, as current results yield from FEM-based is good enough: 

https://arxiv.org/pdf/2403.09964

To be noted, we also find that learning-based correspondence degrade on testing on real datasets, as there is a gap between real and synthetic datasets.

**Comment by zixinyang9109** [comment]
> Thank you for your suggestions, I will try again. Livermatch is a great piece of work, my mentor and I have been studying your work in related fields and we are very inspired by your work. Best wishes for your follow-up work.

Thank you so much! Please let me know if you need any help. Best wishes to your research works too!

**Comment by YueDai0514** [comment]
Thank you for your valuable experience!
